### ISSUE TITLE
如何在view里面include文件

### ISSUE THREAD

**Issue by jiangtao** [ijry/corethink#4]
使用corethink，在view里面include文件，文件引入不起效果。  也没有错误提醒。

**Comment by ijry** [comment]
include按照Tp的规范就好。

**Comment by Jerret321** [comment]
但是 按照tp的规则 是引入的不了的。
比如  我在Public下建了个资源
```php
<include file="__PUBLIC__/tmpl/a.html">
```
是没有办法生效的。

**Comment by ijry** [comment]
路径写死不要用变量

**Comment by Jerret321** [comment]
那岂不是上线还要再改一下路径，这样设计是不是不太合理呢。

**Comment by ijry** [comment]
不是，理论上是没有问题的，官方也有很多用include的，但是你这里出了问题，所以先确认下写死路径是不是正常，万一这都不能include就是别的问题了可能。

**Comment by Jerret321** [comment]
好的 我测试下 告诉您答案

**Comment by ijry** [comment]
试试完整的路径 include ./Application/Test/View/Index/test.html
